// Daily rotating encouragement lines tied to the calendar day
export const RECOVERY_LINES = [
  "Just for today is enough.",
  "You don’t have to solve tomorrow.",
  "Stay where your feet are.",
  "Progress still counts, even when it’s quiet.",
  "Today doesn’t need to be perfect.",
  "Go gently.",
  "This still counts.",
  "Showing up is the work.",
  "Small steps are real steps.",
  "You are allowed to take this one day at a time.",
  "Nothing has to be decided today.",
  "You’re doing the best you can with today.",
  "It’s okay to move slowly.",
  "This moment is survivable.",
  "You don’t have to do this alone.",
  "Rest is part of the work.",
  "Keep what helps. Let the rest go.",
  "You can stop for a breath.",
  "Change adds up.",
  "Time lived differently matters.",
  "This is becoming part of who you are.",
  "You’ve already chosen differently today.",
  "Consistency doesn’t have to be loud.",
  "Steady is strong.",
  "Cravings pass. You stay.",
  "Feelings aren’t commands.",
  "You don’t need to escape this moment.",
  "This wave will break.",
  "Make it to the next ten minutes.",
];

// Short affirmations picked at random each app start
export const AFFIRMATIONS = [
  "You did the hard thing by showing up today.",
  "One honest day at a time is enough.",
  "You are not your past—you are your next choice.",
  "Slow progress is still real progress.",
  "You deserve a life that doesn’t hurt to live.",
  "You’re allowed to be proud of surviving.",
  "Your feelings are real, but they are not a relapse plan.",
  "Today is a chance, not a sentence.",
];
