import { Platform, StyleSheet } from "react-native";

import { palette } from "./theme";

export const appStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: palette.background,
    ...(Platform.OS === "web" ? { minHeight: "100vh" } : null),
  },
  safeArea: {
    flex: 1,
    zIndex: 2,
  },
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 32,
    paddingTop: 60,
    justifyContent: "center",
    alignItems: "stretch",
    gap: 16,
    maxWidth: 820,
    width: "100%",
    alignSelf: "center",
    zIndex: 2,
  },
  headerCopy: {
    alignItems: "center",
    gap: 6,
  },
  primaryLine: {
    color: palette.textPrimary,
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  recoveryLine: {
    color: palette.textFaint,
    fontSize: 13,
    textAlign: "center",
  },
  secondaryLink: {
    marginTop: 6,
  },
  secondaryLinkText: {
    color: palette.accent,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  glowOne: {
    position: "absolute",
    top: -220,
    left: -140,
    width: 320,
    height: 320,
    backgroundColor: palette.accent,
    opacity: 0.1,
    borderRadius: 220,
    shadowColor: palette.accent,
    shadowOpacity: 0.5,
    shadowRadius: 90,
    shadowOffset: { width: 0, height: 0 },
    zIndex: 0,
  },
  glowTwo: {
    position: "absolute",
    bottom: -240,
    right: -140,
    width: 340,
    height: 340,
    backgroundColor: palette.accentDeep,
    opacity: 0.12,
    borderRadius: 260,
    shadowColor: palette.accentDeep,
    shadowOpacity: 0.6,
    shadowRadius: 110,
    shadowOffset: { width: 0, height: 0 },
    zIndex: 0,
  },
  glowThree: {
    position: "absolute",
    bottom: -120,
    left: -160,
    width: 220,
    height: 220,
    backgroundColor: palette.accentSecondary,
    borderRadius: 200,
    shadowColor: palette.accentSecondary,
    shadowOpacity: 0.4,
    shadowRadius: 80,
    shadowOffset: { width: 0, height: 0 },
    zIndex: 0,
  },
  glowFour: {
    position: "absolute",
    bottom: 140,
    left: 120,
    width: 180,
    height: 180,
    backgroundColor: "#5ed0ff",
    borderRadius: 180,
    shadowColor: "#5ed0ff",
    shadowOpacity: 0.35,
    shadowRadius: 70,
    shadowOffset: { width: 0, height: 0 },
    zIndex: 0,
  },
  glowFive: {
    position: "absolute",
    top: -160,
    right: -80,
    width: 160,
    height: 160,
    backgroundColor: "#2dd36f",
    borderRadius: 160,
    shadowColor: "#2dd36f",
    shadowOpacity: 0.35,
    shadowRadius: 70,
    shadowOffset: { width: 0, height: 0 },
    zIndex: 0,
  },
});
